version: '3.8'

services:

  db:
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_dev
    ports:
      - '5432:5432'
